name: 'Mergeable'
description: 'Mergeable helps automate your team''s GitHub workflow without a single line of code.'
inputs:
  config_file:
    description: |
      Allows mergeable configs to be supplied outside of the default path.
      Additional config files need to still be in the .github folder
    required: false
    default: 'mergeable.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
